# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.readcsv:
        class: OCAX\Common\Utils\ReadCSV
        arguments: ['@service_container']
        calls:
            - [setRootdir , ["%kernel.root_dir%"]]
    ocax.config:
        class: OCAX\Common\Utils\ReadConfig
        arguments: ['@service_container']
